version: '3.4'

services:
  reactnotetakingapp:
    image: reacatnotetakingapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: devcontainer
    ports:
      - 3000:3000
      - 9229:9229
    command: ['node', 'inspect-0.0.0.0:9229', 'dist/index.html']
