version: '3.4'

services:
  reactnotetakingapp:
    image: reacatnotetakingapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: devcontainer
    ports:
      - 3000:3000
